Feature/wendy back
AlexSuarezRodriguez/mental-health-back pull request #11
Opened 2022-04-06 02:27 UTC by endyleyms

Configuración para la conección db para los test de back

2022-04-06 04:09 UTC, mhbuiles requested changes

2022-04-06 04:09 UTC, mhbuiles commented on .env
>  SECRET_WORD= wendyalexpooldiegotopv20
El .env no debe subirse al repositorio. Se debe listar este archivo en el .gitignore

2022-04-06 13:49 UTC, endyleyms commented on .env
>  SECRET_WORD= wendyalexpooldiegotopv20
Listo Mateo, ya lo arreglé, gracias!

2022-04-07 02:11 UTC, mhbuiles approved these changes

2022-04-07 02:14 UTC, merged